// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJbZSCV-JgKqU15C0vfs8o3HMmsW0uGdg',
    appId: '1:933621613480:web:ff8484785755a68922139d',
    messagingSenderId: '933621613480',
    projectId: 'chat-app-cde55',
    authDomain: 'chat-app-cde55.firebaseapp.com',
    storageBucket: 'chat-app-cde55.appspot.com',
    measurementId: 'G-5Z7YZ5FLW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1jtIDVVySmgTIXHDTAXW_302LSXFgcc0',
    appId: '1:933621613480:android:fab272576b88ae8722139d',
    messagingSenderId: '933621613480',
    projectId: 'chat-app-cde55',
    storageBucket: 'chat-app-cde55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8VSQExGhSv9LZER99rxvgjBMX5ZJeWGA',
    appId: '1:933621613480:ios:046a063d911b6c3022139d',
    messagingSenderId: '933621613480',
    projectId: 'chat-app-cde55',
    storageBucket: 'chat-app-cde55.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8VSQExGhSv9LZER99rxvgjBMX5ZJeWGA',
    appId: '1:933621613480:ios:4c30a09f6b54ea5e22139d',
    messagingSenderId: '933621613480',
    projectId: 'chat-app-cde55',
    storageBucket: 'chat-app-cde55.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
